---
name: build-docker

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

permissions:
  packages: write

env:
  ARTIFACT_ID: ${{ inputs.ref }}
  ARTIFACT_BASENAME: ghcr.io/link-society/flowg/ci-artifacts

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup@oras
        uses: oras-project/setup-oras@22ce207df3b08e061f537244349aac6ae1d214f6

      - name: login@oras
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printf '%s' "${GITHUB_TOKEN}" | oras login ghcr.io -u ${GITHUB_ACTOR} --password-stdin

      - name: need-website@oras
        id: need-website
        run: |
          if oras repo tags ${ARTIFACT_BASENAME}/website 2>/dev/null | grep -qx "${ARTIFACT_ID}"
          then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: checkout@scm
        if: steps.need-website.outputs.exists == 'false'
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
        with:
          ref: ${{ inputs.ref }}

      - name: setup@buildchain
        if: steps.need-website.outputs.exists == 'false'
        uses: ./.github/actions/setup-buildchain
        with:
          ghtoken: ${{ secrets.GITHUB_TOKEN }}

      - name: download@oras
        if: steps.need-website.outputs.exists == 'false'
        env:
          DEP_ARTIFACT_ID: ${{ inputs.ref }}-linux-amd64
        run: |
          oras pull ${ARTIFACT_BASENAME}/doc-cli:${DEP_ARTIFACT_ID}
          oras pull ${ARTIFACT_BASENAME}/doc-openapi:${DEP_ARTIFACT_ID}

      - name: build@website
        if: steps.need-website.outputs.exists == 'false'
        run: task www:build

      - name: upload@oras
        if: steps.need-website.outputs.exists == 'false'
        run: |
          oras push ${ARTIFACT_BASENAME}/website:${ARTIFACT_ID} \
            website/build
