---
name: ci-main

on:
  push:
    branches:
      - main

jobs:
  build-docker:
    uses: ./.github/workflows/build-docker.yml
    with:
      ref: ${{ github.sha }}

  test:
    needs: build-docker
    uses: ./.github/workflows/test-e2e.yml
    with:
      ref: ${{ github.sha }}

  build-binary:
    uses: ./.github/workflows/build-binary.yml
    with:
      ref: ${{ github.sha }}

  build-website:
    uses: ./.github/workflows/build-website.yml
    needs: build-binary
    with:
      ref: ${{ github.sha }}

  deploy-website:
    uses: ./.github/workflows/deploy-website.yml
    needs: build-website
    with:
      ref: ${{ github.sha }}
