---
name: ci-pr-app

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
    paths-ignore:
      - 'website/**'

jobs:
  build-docker:
    uses: ./.github/workflows/build-docker.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}

  test:
    needs: build-docker
    uses: ./.github/workflows/test-e2e.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}

  security-check:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/security-snyk.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SNYK_ORGANIZATION: ${{ secrets.SNYK_ORGANIZATION }}
