---
name: security-snyk

on:
  - push
  - pull_request

jobs:
  snyk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: checkout@scm
        uses: actions/checkout@v5

      - name: setup@buildchain
        uses: ./.github/actions/setup-buildchain
        with:
          ghtoken: ${{ secrets.GITHUB_TOKEN }}

      - name: setup@snyk
        uses: snyk/actions/setup@master

      - name: login@snyk
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk config set org=${{ secrets.SNYK_ORGANIZATION }}

      - name: prepare@code
        run: task build:frontend

      - name: deps-backend@snyk
        run: snyk test --file=go.mod --sarif-file-output=deps-backend.sarif || true

      - name: deps-frontend@snyk
        run: snyk test --file=web/app/package.json --sarif-file-output=deps-frontend.sarif || true

      - name: code@snyk
        run: snyk code test --sarif-file-output=code.sarif || true

      - name: deps-backend@upload-sarif
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: deps-backend.sarif
          category: deps-backend

      - name: deps-frontend@upload-sarif
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: deps-frontend.sarif
          category: deps-frontend

      - name: code@upload-sarif
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: code.sarif
          category: code
