---
name: security-snyk

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
    secrets:
      SNYK_TOKEN:
        required: true
      SNYK_ORGANIZATION:
        required: true

permissions:
  packages: read
  contents: read
  security-events: write

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: checkout@scm
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
        with:
          ref: ${{ inputs.ref }}

      - name: setup@buildchain
        uses: ./.github/actions/setup-buildchain
        with:
          ghtoken: ${{ secrets.GITHUB_TOKEN }}

      - name: setup@snyk
        uses: snyk/actions/setup@9adf32b1121593767fc3c057af55b55db032dc04

      - name: login@snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORGANIZATION: ${{ secrets.SNYK_ORGANIZATION }}
        run: |
          snyk auth --auth-type=token $SNYK_TOKEN
          snyk config set org=$SNYK_ORGANIZATION

      - name: prepare@code
        run: task build:frontend

      - name: deps-backend@snyk
        run: snyk test --file=go.mod --sarif-file-output=deps-backend.sarif || true

      - name: deps-frontend@snyk
        run: snyk test --file=web/app/package.json --sarif-file-output=deps-frontend.sarif || true

      - name: code@snyk
        run: snyk code test --sarif-file-output=code.sarif || true

      - name: deps-backend@upload-sarif
        uses: github/codeql-action/upload-sarif@014f16e7ab1402f30e7c3329d33797e7948572db
        with:
          sarif_file: deps-backend.sarif
          category: deps-backend

      - name: deps-frontend@upload-sarif
        uses: github/codeql-action/upload-sarif@014f16e7ab1402f30e7c3329d33797e7948572db
        with:
          sarif_file: deps-frontend.sarif
          category: deps-frontend

      - name: code@upload-sarif
        uses: github/codeql-action/upload-sarif@014f16e7ab1402f30e7c3329d33797e7948572db
        with:
          sarif_file: code.sarif
          category: code
