---
name: trigger-release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: cibot@auth
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf
        id: app-token
        with:
          app-id: ${{ secrets.CIBOT_APPID }}
          private-key: ${{ secrets.CIBOT_PRIVKEY }}

      - name: checkout@scm
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: main
          fetch-tags: true

      - name: setup@scm
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          git config --global user.name "link-society[bot]"
          git config --global user.email "noreply@link-society.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - name: tag@scm
        env:
          VERSION: ${{ github.event.inputs.tag }}
        run: |
          echo "${VERSION}" > VERSION.txt
          python scripts/update-security-policy.py --next-release "${VERSION}" > SECURITY.md
          sed -i -E "s/^(version|appVersion): \"v[0-9]+\\.[0-9]+\\.[0-9]+\"/\\1: \"${VERSION}\"/" k8s/charts/flowg/Chart.yaml
          git add VERSION.txt SECURITY.md k8s/charts/flowg/Chart.yaml
          git commit -m ":bookmark: ${VERSION}"
          git push origin main

          git tag ${VERSION}
          git push origin ${VERSION}

      - name: publish@release
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          VERSION: ${{ github.event.inputs.tag }}
        run: |
          gh release create ${VERSION} \
            --generate-notes \
            --latest \
            --discussion-category "Announcements"
